remove ecr from soak-on-release service list (#161)
Description of changes:
* While running soak test on every release of ecr-controller, there were resource leaks and no monitoring was set on those soak tests.
* Since these soak tests were running in isolated e2e test account, it created friction on ecr-controller PR testing
* For now I am removing the soak tests on every release of ecr controller and they can be enabled again once ecr team owns the controller and want this feature.

Error from soak-test-job
```
        # Create k8s resource
        ref = k8s.CustomResourceReference(CRD_GROUP, CRD_VERSION, RESOURCE_PLURAL,resource_name,namespace="default",)
        k8s.create_custom_resource(ref, resource_data)
        cr = k8s.wait_resource_consumed_by_controller(ref)
>      assert cr is not None
E      assert None is not None
tests/test_repository.py:148: AssertionError
 ------------------------------ Captured log call -------------------------------
ERROR    root:resource.py:227 Wait for resource default:ecr-repository-n87zogcx2 to be consumed by controller timed out                                                 
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.