Incompatible quiet flag in docker (#375)
Description of changes:

This removes the quiet flag from the build of the pytest container. Docker reports that the `progress` and `quiet` flags are incompatible.

```Warning: resource namespaces/ack-system is missing the kubectl.kubernetes.io/last-applied-configuration annotation which is required by kubectl apply. kubectl apply should only be used on resources created declaratively by either kubectl create --save-config or kubectl apply. The missing annotation will be patched automatically.
2023-08-21T20:25:49 [INFO] Sleeping for 3000 seconds before rotating temporary aws credentials
2023-08-21T20:25:49 [INFO] Building e2e test container for organizations ...
ERROR: progress=plain and quiet cannot be used together
2023-08-21T20:25:49 [INFO] Running e2e test container for organizations ...
Unable to find image 'ack-test-organizations-b992cb52:latest' locally
docker: Error response from daemon: pull access denied for ack-test-organizations-b992cb52, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.
make: *** [Makefile:26: kind-test] Error 125
```

By submitting this pull request, I confirm that my contribution is made under the terms of the Apache 2.0 license.